src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/District__c.object
<CustomObject>
    <fields>
        <fullName>District_Pin_Code__c</fullName>
        <label>District Pin Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Identification__c</fullName>
        <formula>HYPERLINK( State__r.Country__c,  State__r.Country__r.Name ,&quot;_blank&quot;)+ &quot;=&gt;&quot; +  HYPERLINK( State__c,  State__r.Name ,&quot;_blank&quot;)+ &quot;=&gt;&quot;+ Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Identification</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Districts</relationshipLabel>
        <relationshipName>Districts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Identification__c</fullName>
        <formula>HYPERLINK( Country__c,  Country__r.Name ,&quot;_blank&quot;)+&quot; =&gt; &quot;+Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Identification</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SoqlQueryClass.cls
/**
 *  Purpose         :    This class is used to SOQL
 *  Created By      :    Prem Chand
 *  Created Date    :    2022/07/16
 *  Revision Logs   :    V_1.0 - Created - 2022/07/16
 **/
public with sharing class SoqlQueryClass {

    /**
     * Created By    :    Prem Chand
     * Purpose       :    This method is Child to Parent SOQL using Standard Object
     * Params        :    void
     * Return        :    Void
    **/
    public static void child_To_ParentQueryMethod(){  
        
        List<Contact> conList = [SELECT FirstName, lastName, Account.Name,Account.NumberOfEmployees FROM Contact Limit 1];   // Standard Object
        
        System.debug(conList);   // Child to Parent Query Standard Object
    }

    /**
     * Created By    :    Prem Chand
     * Purpose       :    This method is Child to Parent SOQL using Custom Object
     * Params        :    void
     * Return        :    Void
    **/
    public static void child_To_ParentQueryMethod1(){

        List<State__c> stList = [SELECT Name, Country__r.Name, Country__r.Country_Code__c FROM State__c];   // Custom Object
        System.debug(stList);
    }

    /**
     * Created By    :    Prem Chand
     * Purpose       :    This method is Parent to Child SOQL Using Standard Object
     * Params        :    void
     * Return        :    Void
    **/
    public static void parentTo_ChildQueryMethod(){
        List<Account> accList1 = [SELECT Name,NumberOfEmployees,(SELECT lastName,Email,Phone FROM Contacts) FROM Account]; // Standard Object
        System.debug(accList1);

    }

    /**
     * Created By    :    Prem Chand
     * Purpose       :    This method is Child to Parent SOQL Using Custom Object
     * Params        :    void
     * Return        :    Void
    **/
    public static void parentTo_ChildQueryMethod1(){
        List<State__c> accList2 = [SELECT Name,State_Code__c,(SELECT Name,District_Pin_Code__c,Identification__c FROM Districts__r) FROM State__c]; // Custom Object
        System.debug(accList2);

    }
}